version: "3"

volumes:
  db-store:

services:
  mysql:
    image: mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3326:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sercret
      MYSQL_DATABASE: mysql_sample
      MYSQL_USER: javaer
      MYSQL_PASSWORD: sercret

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 33268:8080

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=javaer
      - PMA_PASSWORD=sercret
    ports:
      - 33269:80
